"use client";
import {useMemo,useState} from "react";
import {ArrowRight,BookOpen,Bus,CheckCircle2,Coffee,FileText,Globe2,GraduationCap,Hospital,Languages,MapPin,Menu,MessageCircle,Moon,Navigation,Search,ShieldAlert,ShoppingBag, Sparkles,Train,WalletCards,X} from "lucide-react";

const universities=["Seoul National University","Korea University","Yonsei University","KAIST","POSTECH","Sungkyunkwan University","Hanyang University","Ewha Womans University"];
const languages=["English","한국어","Қазақша","Русский","Español","Português","Français","中文","日本語","العربية","Deutsch","हिन्दी","Bahasa Indonesia","Tiếng Việt","Türkçe","বাংলা"];
const places=[
 {name:"Student Mart",cat:"shopping",info:"2 min walk • essentials",icon:ShoppingBag},
 {name:"Campus Café",cat:"food",info:"4 min walk • study friendly",icon:Coffee},
 {name:"Halal Kitchen",cat:"halal",info:"7 min walk • halal",icon:Coffee},
 {name:"University Hospital",cat:"hospital",info:"9 min walk • emergency care",icon:Hospital},
 {name:"CU Convenience Store",cat:"24/7",info:"3 min walk • open 24/7",icon:Moon},
 {name:"ATM / Bank",cat:"bank",info:"5 min walk",icon:WalletCards},
 {name:"Central Library",cat:"study",info:"6 min walk • study space",icon:BookOpen},
 {name:"Metro Station",cat:"transport",info:"8 min walk",icon:Train}
];
const tasks=["Check passport validity","Prepare apostilled documents","Confirm university admission","Prepare arrival plan","Learn basic Korean phrases"];

export default function Home(){
 const [uni,setUni]=useState(universities[0]); const [lang,setLang]=useState("English"); const [filter,setFilter]=useState("all"); const [q,setQ]=useState(""); const [chat,setChat]=useState(false); const [emergency,setEmergency]=useState(false); const [menu,setMenu]=useState(false);
 const visible=useMemo(()=>places.filter(p=>(filter==="all"||p.cat===filter)&&(`${p.name} ${p.info}`).toLowerCase().includes(q.toLowerCase())),[filter,q]);
 return <main className="min-h-screen bg-slate-950">
  <header className="sticky top-0 z-40 border-b border-white/10 bg-slate-950/90 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 sm:px-6">
   <a href="#top" className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-sky-400 text-slate-950"><GraduationCap/></span><span><b>GKS Campus Bridge</b><small className="block text-xs text-slate-500">Your Korea student companion</small></span></a>
   <nav className="hidden gap-6 text-sm text-slate-300 md:flex"><a href="#map">Campus Map</a><a href="#tasks">Tasks</a><a href="#tools">Toolkit</a></nav>
   <div className="hidden items-center gap-2 sm:flex"><div className="flex items-center gap-2 rounded-xl border border-white/10 px-3 py-2"><Languages size={16}/><select value={lang} onChange={e=>setLang(e.target.value)} className="bg-transparent text-sm outline-none">{languages.map(x=><option className="bg-slate-900" key={x}>{x}</option>)}</select></div><button onClick={()=>setEmergency(true)} className="rounded-xl border border-red-400/30 px-3 py-2 text-sm text-red-300"><ShieldAlert size={16} className="mr-2 inline"/>Emergency</button></div>
   <button onClick={()=>setMenu(!menu)} className="rounded-xl border border-white/10 p-2 md:hidden">{menu?<X/>:<Menu/>}</button>
  </div>{menu&&<div className="border-t border-white/10 p-4 md:hidden"><div className="flex flex-col gap-4 text-sm"><a href="#map">Campus Map</a><a href="#tasks">Tasks</a><a href="#tools">Toolkit</a><button className="text-left text-red-300" onClick={()=>setEmergency(true)}>Emergency</button></div></div>}</header>

  <section id="top" className="mx-auto max-w-7xl px-4 py-16 sm:px-6"><div className="grid gap-8 lg:grid-cols-[1.4fr_.6fr]">
   <div><div className="mb-5 inline-flex items-center gap-2 rounded-full bg-sky-400/10 px-3 py-2 text-sm text-sky-300"><Sparkles size={15}/>Built for international GKS scholars</div><h1 className="text-4xl font-black tracking-tight sm:text-6xl">Your journey to Korea,<span className="block text-sky-400">all in one place.</span></h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-400">Prepare documents, understand campus life, find useful places, manage tasks and get student guidance.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#map" className="rounded-xl bg-sky-400 px-5 py-3 font-bold text-slate-950">Explore my campus <ArrowRight size={18} className="inline"/></a><button onClick={()=>setChat(true)} className="rounded-xl border border-white/10 px-5 py-3"><MessageCircle size={18} className="mr-2 inline"/>Ask AI</button></div></div>
   <div className="rounded-3xl border border-white/10 bg-white/[.04] p-6"><p className="text-sm text-slate-400">GKS Journey</p><h2 className="mt-1 text-2xl font-bold">68% complete</h2><div className="mt-6 h-3 rounded-full bg-slate-800"><div className="h-full w-[68%] rounded-full bg-sky-400"/></div><div className="mt-6 space-y-4">{["Application","Selection","University","Pre-departure","Arrival in Korea"].map((x,i)=><div key={x} className="flex gap-3"><span className={`mt-1 h-3 w-3 rounded-full ${i<3?"bg-sky-400":"bg-slate-700"}`}/><span className={i<3?"text-slate-200":"text-slate-500"}>{x}</span></div>)}</div></div>
  </div></section>

  <section className="mx-auto max-w-7xl px-4 pb-8 sm:px-6"><div className="grid gap-4 sm:grid-cols-3"><Stat icon={WalletCards} label="Monthly budget" value="₩900,000"/><Stat icon={FileText} label="Documents ready" value="12 / 15"/><Stat icon={CheckCircle2} label="Tasks completed" value="3 / 5"/></div></section>

  <section id="map" className="mx-auto max-w-7xl px-4 py-12 sm:px-6"><div className="mb-6 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-semibold uppercase tracking-wider text-sky-400">Smart Campus Map</p><h2 className="mt-2 text-3xl font-bold">Everything around your university</h2><p className="mt-2 text-slate-400">Select your university and explore useful places.</p></div><div className="relative lg:w-[360px]"><GraduationCap className="absolute left-3 top-3" size={18}/><select value={uni} onChange={e=>setUni(e.target.value)} className="w-full rounded-xl border border-white/10 bg-white/5 py-3 pl-10 pr-3 text-sm outline-none">{universities.map(x=><option className="bg-slate-900" key={x}>{x}</option>)}</select></div></div>
   <div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><div className="relative min-h-[430px] overflow-hidden rounded-3xl border border-white/10 bg-slate-900" style={{backgroundImage:"linear-gradient(to right,rgba(148,163,184,.12) 1px,transparent 1px),linear-gradient(to bottom,rgba(148,163,184,.12) 1px,transparent 1px)",backgroundSize:"55px 55px"}}><div className="absolute left-[45%] top-[42%] text-center"><div className="mx-auto w-fit rounded-full bg-sky-400 p-3 text-slate-950"><GraduationCap/></div><span className="mt-2 block rounded bg-slate-950/90 px-3 py-1 text-xs">{uni}</span></div>{[["18%","25%","Shop"],["72%","22%","Food"],["75%","68%","Hospital"],["28%","72%","Metro"],["58%","82%","Library"],["14%","56%","ATM"]].map(([l,t,n])=><div key={n} className="absolute" style={{left:l,top:t}}><div className="h-3 w-3 rounded-full bg-white"/><span className="text-[10px] text-slate-400">{n}</span></div>)}<span className="absolute bottom-4 left-4 rounded-lg bg-slate-950/80 px-3 py-2 text-xs text-slate-500">Demo map • real map can be connected later</span></div>
    <div className="rounded-3xl border border-white/10 bg-white/[.04] p-5"><div className="relative"><Search className="absolute left-3 top-3" size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search nearby places..." className="w-full rounded-xl border border-white/10 bg-slate-950 py-3 pl-10 text-sm outline-none"/></div><div className="mt-4 flex gap-2 overflow-x-auto">{[["all","All"],["food","Food"],["halal","Halal"],["shopping","Shopping"],["24/7","24/7"],["hospital","Hospital"]].map(([v,n])=><button key={v} onClick={()=>setFilter(v)} className={`whitespace-nowrap rounded-full px-3 py-1.5 text-xs ${filter===v?"bg-sky-400 font-bold text-slate-950":"bg-white/5 text-slate-400"}`}>{n}</button>)}</div><div className="mt-5 space-y-3">{visible.map(p=>{const Icon=p.icon;return <div key={p.name} className="flex items-center gap-3 rounded-2xl bg-slate-950/60 p-3"><div className="rounded-xl bg-sky-400/10 p-2.5 text-sky-300"><Icon size={18}/></div><div className="min-w-0 flex-1"><b className="block truncate">{p.name}</b><small className="text-xs text-slate-500">{p.info}</small></div><Navigation size={16} className="text-slate-600"/></div>})}</div></div>
   </div></section>

  <section id="tasks" className="mx-auto max-w-7xl px-4 py-12 sm:px-6"><div className="grid gap-5 lg:grid-cols-2"><div className="rounded-3xl border border-white/10 bg-white/[.04] p-6"><h2 className="text-2xl font-bold">Pre-departure tasks</h2><div className="mt-5 space-y-3">{tasks.map((x,i)=><div key={x} className="flex items-center gap-3 rounded-xl bg-slate-950/60 p-3"><CheckCircle2 size={19} className={i<3?"text-sky-400":"text-slate-700"}/><span className={i<3?"line-through text-slate-400":"text-slate-200"}>{x}</span></div>)}</div></div><div id="tools" className="rounded-3xl border border-sky-400/20 bg-sky-400/5 p-6"><Sparkles className="text-sky-400"/><h2 className="mt-4 text-2xl font-bold">AI Student Assistant</h2><p className="mt-3 text-slate-400">Ask about documents, Korean phrases, budgeting, transportation or university life.</p><button onClick={()=>setChat(true)} className="mt-6 rounded-xl bg-sky-400 px-5 py-3 font-bold text-slate-950">Open AI Assistant <ArrowRight size={18} className="inline"/></button></div></div></section>

  <footer className="border-t border-white/10 py-8 text-center text-sm text-slate-500">GKS Campus Bridge • Student project prototype</footer>
  {chat&&<Modal title="AI Student Assistant" close={()=>setChat(false)}><div className="rounded-2xl bg-slate-950 p-4 text-sm text-slate-300"><b className="text-sky-300">GKS AI</b><p className="mt-2">Hi! Try asking: “What should I prepare before arriving in Korea?”</p></div><input placeholder="Ask a question..." className="mt-4 w-full rounded-xl border border-white/10 bg-slate-950 p-3 text-sm"/><p className="mt-2 text-xs text-slate-600">Demo interface — connect an AI API later.</p></Modal>}
  {emergency&&<Modal title="Emergency Mode" close={()=>setEmergency(false)}><div className="grid gap-3 sm:grid-cols-2"><a href="tel:112" className="rounded-2xl bg-red-500/10 p-5"><b className="text-2xl text-red-300">112</b><span className="block text-sm text-slate-400">Police</span></a><a href="tel:119" className="rounded-2xl bg-red-500/10 p-5"><b className="text-2xl text-red-300">119</b><span className="block text-sm text-slate-400">Fire / Ambulance</span></a></div></Modal>}
 </main>
}
function Stat({icon:Icon,label,value}:{icon:React.ElementType;label:string;value:string}){return <div className="rounded-2xl border border-white/10 bg-white/[.04] p-5"><div className="flex items-center gap-3 text-slate-400"><Icon size={19}/>{label}</div><div className="mt-4 text-2xl font-bold">{value}</div></div>}
function Modal({title,children,close}:{title:string;children:React.ReactNode;close:()=>void}){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><div className="w-full max-w-lg rounded-3xl border border-white/10 bg-slate-900 p-6"><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-bold">{title}</h2><button onClick={close}><X/></button></div>{children}</div></div>}
